version: '3.9'

services:
  the-drone:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/the-drone-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=the-drone
      - POSTGRES_USER=the-drone
      - POSTGRES_DB=the-drone